// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "10001",
    name: "Abdul Rahman",
    email: "abdul@rahman.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01711111111",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "45 Gulshan, Dhaka, Bangladesh",
  },
  {
    id: 2,
    teacherId: "10002",
    name: "Fatema Khatun",
    email: "fatema@khatun.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01722222222",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "22 Agrabad, Chittagong, Bangladesh",
  },
  {
    id: 3,
    teacherId: "10003",
    name: "Mizanur Rahman",
    email: "mizanur@rahman.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01733333333",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "12 Ambarkhana, Sylhet, Bangladesh",
  },
  {
    id: 4,
    teacherId: "10004",
    name: "Shirin Akter",
    email: "shirin@akter.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01744444444",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "35 Amtala, Barisal, Bangladesh",
  },
  {
    id: 5,
    teacherId: "10005",
    name: "Mohammad Ali",
    email: "mohammad@ali.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01755555555",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "98 Rupsha, Khulna, Bangladesh",
  },
  {
    id: 6,
    teacherId: "10006",
    name: "Nazma Begum",
    email: "nazma@begum.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01766666666",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "29 Sapura, Rajshahi, Bangladesh",
  },
  {
    id: 7,
    teacherId: "10007",
    name: "Abul Bashar",
    email: "abul@bashar.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01777777777",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "50 Kandirpar, Comilla, Bangladesh",
  },
  {
    id: 8,
    teacherId: "10008",
    name: "Rokeya Banu",
    email: "rokeya@banu.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01788888888",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "17 Station Road, Rangpur, Bangladesh",
  },
  {
    id: 9,
    teacherId: "10009",
    name: "Habib Ullah",
    email: "habib@ullah.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01799999999",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "64 Ram Babu Road, Mymensingh, Bangladesh",
  },
  {
    id: 10,
    teacherId: "10010",
    name: "Rashid Khan",
    email: "rashid@khan.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01710101010",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "23 Jessore Cantonment, Jessore, Bangladesh",
  },
  {
    id: 11,
    teacherId: "10011",
    name: "Shakil Ahmed",
    email: "shakil@ahmed.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01755555666",
    subjects: ["Bangla"],
    classes: ["3A", "2B"],
    address: "45 Mirpur, Dhaka, Bangladesh",
  },
  {
    id: 12,
    teacherId: "10012",
    name: "Imam Hossain",
    email: "imam@hossain.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01766666777",
    subjects: ["Islam"],
    classes: ["4A", "5A"],
    address: "22 Uttara, Dhaka, Bangladesh",
  },
];



export const studentsData = [
  {
    id: 1,
    studentId: "101",
    name: "Sakib Ahmed",
    email: "sakib@ahmed.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01711111111",
    grade: 5,
    class: "5B",
    address: "45 Gulshan, Dhaka, Bangladesh",
  },
  {
    id: 2,
    studentId: "102",
    name: "Ayesha Siddiqui",
    email: "ayesha@siddiqui.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01722222222",
    grade: 5,
    class: "5A",
    address: "22 Agrabad, Chittagong, Bangladesh",
  },
  {
    id: 3,
    studentId: "103",
    name: "Rafiq Hasan",
    email: "rafiq@hasan.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01733333333",
    grade: 5,
    class: "5A",
    address: "12 Ambarkhana, Sylhet, Bangladesh",
  },
  {
    id: 4,
    studentId: "104",
    name: "Farhana Akter",
    email: "farhana@akter.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01744444444",
    grade: 5,
    class: "5A",
    address: "35 Amtala, Barisal, Bangladesh",
  },
  {
    id: 5,
    studentId: "105",
    name: "Jamil Rahman",
    email: "jamil@rahman.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01755555555",
    grade: 5,
    class: "5A",
    address: "98 Rupsha, Khulna, Bangladesh",
  },
  {
    id: 6,
    studentId: "106",
    name: "Zahid Karim",
    email: "zahid@karim.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01766666666",
    grade: 5,
    class: "5A",
    address: "29 Sapura, Rajshahi, Bangladesh",
  },
  {
    id: 7,
    studentId: "107",
    name: "Tasnim Alam",
    email: "tasnim@alam.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01777777777",
    grade: 5,
    class: "5A",
    address: "50 Kandirpar, Comilla, Bangladesh",
  },
  {
    id: 8,
    studentId: "108",
    name: "Tanvir Hossain",
    email: "tanvir@hossain.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01788888888",
    grade: 5,
    class: "5A",
    address: "17 Station Road, Rangpur, Bangladesh",
  },
  {
    id: 9,
    studentId: "109",
    name: "Sabrina Jahan",
    email: "sabrina@jahan.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01799999999",
    grade: 5,
    class: "5A",
    address: "64 Ram Babu Road, Mymensingh, Bangladesh",
  },
  {
    id: 10,
    studentId: "110",
    name: "Mehedi Hasan",
    email: "mehedi@hasan.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "01710101010",
    grade: 5,
    class: "5A",
    address: "23 Jessore Cantonment, Jessore, Bangladesh",
  },
];


export const parentsData = [
  {
    id: 1,
    name: "Abdul Rahman",
    students: ["Sakib Ahmed"],
    email: "abdul@rahman.com",
    phone: "01711111111",
    address: "45 Gulshan, Dhaka, Bangladesh",
    district: "Dhaka",
  },
  {
    id: 2,
    name: "Fatema Khatun",
    students: ["Ayesha Siddiqui"],
    email: "fatema@khatun.com",
    phone: "01722222222",
    address: "22 Agrabad, Chittagong, Bangladesh",
    district: "Chittagong",
  },
  {
    id: 3,
    name: "Mizanur Rahman",
    students: ["Rafiq Hasan"],
    email: "mizanur@rahman.com",
    phone: "01733333333",
    address: "12 Ambarkhana, Sylhet, Bangladesh",
    district: "Sylhet",
  },
  {
    id: 4,
    name: "Shirin Akter",
    students: ["Farhana Akter", "Iqbal Hossain"],
    email: "shirin@akter.com",
    phone: "01744444444",
    address: "35 Amtala, Barisal, Bangladesh",
    district: "Barisal",
  },
  {
    id: 5,
    name: "Mohammad Ali",
    students: ["Jamil Rahman"],
    email: "mohammad@ali.com",
    phone: "01755555555",
    address: "98 Rupsha, Khulna, Bangladesh",
    district: "Khulna",
  },
  {
    id: 6,
    name: "Nazma Begum",
    students: ["Zahid Karim"],
    email: "nazma@begum.com",
    phone: "01766666666",
    address: "29 Sapura, Rajshahi, Bangladesh",
    district: "Rajshahi",
  },
  {
    id: 7,
    name: "Abul Bashar",
    students: ["Tasnim Alam", "Sumaiya Bashar"],
    email: "abul@bashar.com",
    phone: "01777777777",
    address: "50 Kandirpar, Comilla, Bangladesh",
    district: "Comilla",
  },
  {
    id: 8,
    name: "Rokeya Banu",
    students: ["Tanvir Hossain"],
    email: "rokeya@banu.com",
    phone: "01788888888",
    address: "17 Station Road, Rangpur, Bangladesh",
    district: "Rangpur",
  },
  {
    id: 9,
    name: "Habib Ullah",
    students: ["Sabrina Jahan", "Nadia Akter"],
    email: "habib@ullah.com",
    phone: "01799999999",
    address: "64 Ram Babu Road, Mymensingh, Bangladesh",
    district: "Mymensingh",
  },
  {
    id: 10,
    name: "Rashid Khan",
    students: ["Mehedi Hasan"],
    email: "rashid@khan.com",
    phone: "01710101010",
    address: "23 Jessore Cantonment, Jessore, Bangladesh",
    district: "Jessore",
  },
  {
    id: 11,
    name: "Kamrul Islam",
    students: ["Shafayat Islam"],
    email: "kamrul@islam.com",
    phone: "01711122233",
    address: "67 Patgudam, Mymensingh, Bangladesh",
    district: "Mymensingh",
  },
  {
    id: 12,
    name: "Lutfar Rahman",
    students: ["Munia Rahman"],
    email: "lutfar@rahman.com",
    phone: "01722334455",
    address: "13 Majher Char, Noakhali, Bangladesh",
    district: "Noakhali",
  },
  {
    id: 13,
    name: "Sharmin Akhter",
    students: ["Tanim Khan"],
    email: "sharmin@akhter.com",
    phone: "01733445566",
    address: "25 Azimpur, Dhaka, Bangladesh",
    district: "Dhaka",
  },
  {
    id: 14,
    name: "Aminul Haque",
    students: ["Rokib Haque", "Samira Haque"],
    email: "aminul@haque.com",
    phone: "01744556677",
    address: "78 Bashundhara, Dhaka, Bangladesh",
    district: "Dhaka",
  },
  {
    id: 15,
    name: "Nasima Banu",
    students: ["Arman Hossain"],
    email: "nasima@banu.com",
    phone: "01755667788",
    address: "44 Kushtia Sadar, Kushtia, Bangladesh",
    district: "Kushtia",
  },
  {
    id: 16,
    name: "Rezaul Karim",
    students: ["Mahmud Karim"],
    email: "rezaul@karim.com",
    phone: "01766778899",
    address: "12 Uzirpur, Barisal, Bangladesh",
    district: "Barisal",
  },
  {
    id: 17,
    name: "Meherun Nesa",
    students: ["Israt Jahan"],
    email: "meherun@nesa.com",
    phone: "01777889900",
    address: "30 Pirojpur Road, Pirojpur, Bangladesh",
    district: "Pirojpur",
  },
  {
    id: 18,
    name: "Golam Mostafa",
    students: ["Ashraf Mostafa"],
    email: "golam@mostafa.com",
    phone: "01788990011",
    address: "19 Nawabganj, Dhaka, Bangladesh",
    district: "Dhaka",
  },
  {
    id: 19,
    name: "Jannatul Ferdous",
    students: ["Naimur Rahman"],
    email: "jannatul@ferdous.com",
    phone: "01799001122",
    address: "22 Bhaluka, Mymensingh, Bangladesh",
    district: "Mymensingh",
  },
  {
    id: 20,
    name: "Shahidul Islam",
    students: ["Imtiaz Islam"],
    email: "shahidul@islam.com",
    phone: "01710112233",
    address: "55 Baro Bazar, Narail, Bangladesh",
    district: "Narail",
  },
];


export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Abdul Rahman", "Rokeya Begum"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Allen Hossain", "Farhana Akter"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Fatema Khatun", "Shahab Uddin"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Rezaul Karim", "Mahmudul Hasan"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Mizanur Rahman", "Jannatul Ferdous"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Shirin Akter", "Nazma Begum"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lutfar Rahman", "Nasima Banu"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Rasheda Parvin", "Shirin Akter"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Rokeya Begum", "Nazmul Haque"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Jahid Hasan", "Farhana Akter"],
  },
  {
    id: 11,
    name: "Bangla",
    teachers: ["Shakil Ahmed", "Nasima Begum"],
  },
  {
    id: 12,
    name: "Islam",
    teachers: ["Imam Hossain", "Rahima Khatun"],
  },
];


export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Abdul Rahman",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Fatema Khatun",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Mizanur Rahman",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Jane Smith",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Shirin Akter",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Rezaul Karim",
  },
];


export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1B",
    teacher: "Abdul Rahman",
  },
  {
    id: 2,
    subject: "English",
    class: "5A",
    teacher: "Allen Black",
  },
  {
    id: 3,
    subject: "Biology",
    class: "5A",
    teacher: "Mizanur Rahman",
  },
  {
    id: 4,
    subject: "History",
    class: "5A",
    teacher: "Shirin Akter",
  },
  {
    id: 5,
    subject: "Art",
    class: "4B",
    teacher: "Jane Smith",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Anna Santiago",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shirin Akter",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
  },
  {
    id: 9,
    subject: "Physics",
    class: "5A",
    teacher: "Fatema Khatun",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "5A",
    teacher: "Fatema Khatun",
  },
  {
    id: 11,
    subject: "Bangla",
    class: "3A",
    teacher: "Nasima Banu",
  },
  {
    id: 12,
    subject: "Islam",
    class: "4A",
    teacher: "Rezaul Karim",
  },
];


export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1B",
    teacher: "Abdul Rahman",
    date: "2025-01-15",
  },
  {
    id: 2,
    subject: "English",
    class: "5A",
    teacher: "Allen Black",
    date: "2025-01-20",
  },
  {
    id: 3,
    subject: "Biology",
    class: "5A",
    teacher: "Mizanur Rahman",
    date: "2025-01-22",
  },
  {
    id: 4,
    subject: "History",
    class: "5A",
    teacher: "Shirin Akter",
    date: "2025-01-25",
  },
  {
    id: 5,
    subject: "Art",
    class: "4B",
    teacher: "Jane Smith",
    date: "2025-02-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Anna Santiago",
    date: "2025-02-05",
  },
  {
    id: 7,
    subject: "History",
    class: "5A",
    teacher: "Shirin Akter",
    date: "2025-02-10",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    date: "2025-02-15",
  },
  {
    id: 9,
    subject: "Physics",
    class: "5A",
    teacher: "Fatema Khatun",
    date: "2025-02-20",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "5A",
    teacher: "Fatema Khatun",
    date: "2025-02-25",
  },
];


export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1B",
    teacher: "Abdul Rahman",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "5A",
    teacher: "Allen Black",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Biology",
    class: "5A",
    teacher: "Mizanur Rahman",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "History",
    class: "5A",
    teacher: "Shirin Akter",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4B",
    teacher: "Jane Smith",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Anna Santiago",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "5A",
    teacher: "Shirin Akter",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "5A",
    teacher: "Fatema Khatun",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "5A",
    teacher: "Fatema Khatun",
    dueDate: "2025-01-01",
  },
];


export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1B",
    teacher: "Abdul Rahman",
    student: "Sakib Ahmed",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "Physics",
    class: "5A",
    teacher: "Fatema Khatun",
    student: "Ayesha Siddiqui",
    date: "2025-01-01",
    type: "exam",
    score: 88,
  },
  {
    id: 3,
    subject: "Biology",
    class: "5A",
    teacher: "Mizanur Rahman",
    student: "Rafiq Hasan",
    date: "2025-01-01",
    type: "exam",
    score: 92,
  },
  {
    id: 4,
    subject: "History",
    class: "5A",
    teacher: "Shirin Akter",
    student: "Farhana Akter",
    date: "2025-01-01",
    type: "exam",
    score: 85,
  },
  {
    id: 5,
    subject: "Music",
    class: "4B",
    teacher: "Jane Smith",
    student: "Jamil Rahman",
    date: "2025-01-01",
    type: "exam",
    score: 93,
  },
  {
    id: 6,
    subject: "Physics",
    class: "5A",
    teacher: "Anna Santiago",
    student: "Zahid Karim",
    date: "2025-01-01",
    type: "exam",
    score: 89,
  },
  {
    id: 7,
    subject: "English",
    class: "5A",
    teacher: "Allen Black",
    student: "Tasnim Alam",
    date: "2025-01-01",
    type: "exam",
    score: 87,
  },
  {
    id: 8,
    subject: "Math",
    class: "5A",
    teacher: "Ophelia Castro",
    student: "Tanvir Hossain",
    date: "2025-01-01",
    type: "exam",
    score: 91,
  },
  {
    id: 9,
    subject: "English",
    class: "5A",
    teacher: "Derek Briggs",
    student: "Sabrina Jahan",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Biology",
    class: "5A",
    teacher: "John Glover",
    student: "Mehedi Hasan",
    date: "2025-01-01",
    type: "exam",
    score: 92,
  },
];


export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 12, 8, 0),
    end: new Date(2024, 7, 12, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];